{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Automatyczne Tworzenie Ticketów' %}{% endblock %}

{% set active_menu = 'autoticket' %}

{% block content %}

<div class="widget first">
    <div class="head">
        <h5>{% trans 'Automatyczne Tworzenie Ticketów' %}</h5>
    </div>

    <div class="help">
        <h3>{% trans 'Tu są informacje jakie zostały pobrane z e-maila' %}</h3>
    </div>

     <table class="tableStatic wide">
        <tbody>
            <tr class="noborder">
                <td>{% trans 'Date' %}</td>
                <td align="right">{{ Date }}</td>
            </tr>

            <tr>
                <td>{% trans 'Driver' %}</td>
                <td align="right">{{ Driver }}</td>
            </tr>
            
            <tr>
                <td>{% trans 'Mailbox' %}</td>
                <td align="right">{{ Mailbox }}</td>
            </tr>
            
            <tr>
                <td>{% trans 'Messages' %}</td>
                <td align="right">{{ Messages }}</td>
            </tr>
            
            <tr>
                <td>{% trans 'Recent' %}</td>
                <td align="right">{{ Recent }}</td>
            </tr>
            
            <tr>
                <td>{% trans 'Unread' %}</td>
                <td align="right">{{ Unread }}</td>
            </tr>
            
             <tr>
                <td>{% trans 'Deleted' %}</td>
                <td align="right">{{ Deleted }}</td>
            </tr>
            
            <tr>
                <td>{% trans 'Size' %}</td>
                <td align="right"><pre>{{ Size }}</pre></td>
            </tr>
        </tbody>
		<tfoot>
            <tr>
                <td colspan="2">
                    <div class="aligncenter">
                    <a href="{{ 'autoticket'|alink }}" title="" class="btn55 mr10"><img src="images/icons/middlenav/airplane.png" alt=""><span>{% trans 'Wróc' %}</span></a>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
    
</div>

{% endblock %}